version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "javascript"
      - "typescript"
    groups:
      typescript:
        patterns:
          - "@types/*"
          - "typescript"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "cypress"
          - "jsdom"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "terser"
          - "eslint*"
        update-types:
          - "minor"
          - "patch"
    allow:
      - dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
