# Site settings
title: Simple Jekyll Search
email: your-email@domain.com
description: A simple search solution for Jekyll sites
baseurl: "/Simple-Jekyll-Search"
url: "https://sylhare.github.io"

# Build settings
markdown: kramdown
sass:
  style: compressed